commit 85bd97523894222c765a31a8d96da277f93be26e
Author: Andrei Lukovenko <aluck@cordeo.ru>
Date:   Mon Jul 11 01:26:31 2016 +0200

    Bug: invocation with state=absent always leads to (#3051)
    
    [localhost]: FAILED! => {"changed": false, "failed": true, "msg":
    "'Domain' object has no attribute 'id'"}
    
    How to reproduce:
    
    - name: create domain
      digital_ocean_domain: state=present name=DOMAIN_NAME ip=DROPLET_IP
    
    - name: destroy domain
      digital_ocean_domain: state=absent name=DOMAIN_NAME
    
    Problem: DigitalOcean API accepts domain name, not record ID
    (https://developers.digitalocean.com/documentation/v2/#delete-a-domain)

diff --git a/lib/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py b/lib/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py
index 81de784af8..cf05a7f91c 100644
--- a/lib/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py
+++ b/lib/ansible/modules/cloud/digital_ocean/digital_ocean_domain.py
@@ -125,7 +125,7 @@ class Domain(JsonfyMixIn):
         self.__dict__.update(domain_json)
 
     def destroy(self):
-        self.manager.destroy_domain(self.id)
+        self.manager.destroy_domain(self.name)
 
     def records(self):
         json = self.manager.all_domain_records(self.id)
@@ -177,7 +177,6 @@ def core(module):
     except KeyError as e:
         module.fail_json(msg='Unable to load %s' % e.message)
 
-    changed = True
     state = module.params['state']
 
     Domain.setup(api_token)
