commit dfabf2707a47367cbaf0181fed81fca82a41759a
Author: Stephen Paul Suarez <devpopol@gmail.com>
Date:   Wed Jun 25 14:20:07 2014 +0800

    fixes the now-incorrect module for ApiError
    
    https://github.com/dotcloud/docker-py/blob/0.3.2/docker/errors.py
    - ApiError is now(0.3.2) under the docker.errors

diff --git a/library/cloud/docker_image b/library/cloud/docker_image
index 1727486f8a..512f17cfd1 100644
--- a/library/cloud/docker_image
+++ b/library/cloud/docker_image
@@ -235,7 +235,7 @@ def main():
 
         module.exit_json(failed=failed, changed=manager.has_changed(), msg=msg, image_id=image_id)
 
-    except docker.client.APIError as e:
+    except docker.errors.APIError as e:
         module.exit_json(failed=True, changed=manager.has_changed(), msg="Docker API error: " + e.explanation)
 
     except RequestException as e:
