commit 7b484e01b20f711a17703391db42a77856e8ef7d
Author: Wes McKinney <wesmckinn@gmail.com>
Date:   Tue Jun 19 17:21:02 2012 -0400

    BUG: raise exception in DataFrame.fillna when axis=1 and pass dict/Series. close #1485

diff --git a/pandas/core/frame.py b/pandas/core/frame.py
index 3cf4b1584..302b1e03f 100644
--- a/pandas/core/frame.py
+++ b/pandas/core/frame.py
@@ -2750,6 +2750,11 @@ class DataFrame(NDFrame):
             if len(self.columns) == 0:
                 return self
             if isinstance(value, (dict, Series)):
+                if axis == 1:
+                    raise NotImplementedError('Currently only can fill '
+                                              'with dict/Series column '
+                                              'by column')
+
                 result = self if inplace else self.copy()
                 for k, v in value.iteritems():
                     if k not in result:
diff --git a/pandas/tests/test_frame.py b/pandas/tests/test_frame.py
index 7716f5181..cb3ee628c 100644
--- a/pandas/tests/test_frame.py
+++ b/pandas/tests/test_frame.py
@@ -5,13 +5,12 @@ from StringIO import StringIO
 import cPickle as pickle
 import operator
 import os
-import sys
 import unittest
 
 import nose
 
 from numpy import random, nan
-from numpy.random import randn, randint
+from numpy.random import randn
 import numpy as np
 import numpy.ma as ma
 
@@ -3868,6 +3867,9 @@ class TestDataFrame(unittest.TestCase, CheckIndexing,
         expected = df.fillna(df.max().to_dict())
         assert_frame_equal(result, expected)
 
+        # disable this for now
+        self.assertRaises(Exception, df.fillna, df.max(1), axis=1)
+
     def test_fillna_columns(self):
         df = DataFrame(np.random.randn(10, 10))
         df.values[:, ::2] = np.nan
