commit 1ed90b1a79ed6f119a7e1eda0d966a7b68f8869b
Author: David Cramer <dcramer@gmail.com>
Date:   Fri Apr 17 15:59:35 2015 -0700

    Correct how context is handled with exceptions

diff --git a/src/sentry/interfaces/exception.py b/src/sentry/interfaces/exception.py
index 18c7633452..b9d170fafb 100644
--- a/src/sentry/interfaces/exception.py
+++ b/src/sentry/interfaces/exception.py
@@ -70,6 +70,19 @@ class SingleException(Interface):
             'stacktrace': stacktrace,
         }
 
+    def get_api_context(self):
+        if self.stacktrace:
+            stacktrace = self.stacktrace.get_api_context()
+        else:
+            stacktrace = None
+
+        return {
+            'type': self.type,
+            'value': self.value,
+            'module': self.module,
+            'stacktrace': stacktrace,
+        }
+
     def get_alias(self):
         return 'exception'
 
@@ -178,6 +191,12 @@ class Exception(Interface):
             'exc_omitted': self.exc_omitted,
         }
 
+    def get_api_context(self):
+        return {
+            'values': [v.get_api_context() for v in self.values],
+            'excOmitted': self.exc_omitted,
+        }
+
     def __getitem__(self, key):
         return self.values[key]
 
